// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3jsyECFVlvXhy9TKIRTX42eRlRbH3_A',
    appId: '1:494792759008:web:8fe7e002d06c46eddea285',
    messagingSenderId: '494792759008',
    projectId: 'identalfb',
    authDomain: 'identalfb.firebaseapp.com',
    storageBucket: 'identalfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjf0UCf0lHa24edXWPlME8cW8hS-yUtjI',
    appId: '1:494792759008:android:e6a98e1251566d28dea285',
    messagingSenderId: '494792759008',
    projectId: 'identalfb',
    storageBucket: 'identalfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBveh6NzSsZzpdPyilfGxNr0RyDUlMto',
    appId: '1:494792759008:ios:134efb90e072cbb0dea285',
    messagingSenderId: '494792759008',
    projectId: 'identalfb',
    storageBucket: 'identalfb.appspot.com',
    iosClientId: '494792759008-ubctpu96j8uqn8e7eq7mglm6l4cvbco9.apps.googleusercontent.com',
    iosBundleId: 'space.artemdev.idental',
  );
}
